Homework Ten
DariaChapek/Chapek_AQA pull request #2
Opened 2020-05-07 17:42 UTC by DariaChapek

Exceptions

2020-05-08 09:52 UTC, marisita requested changes
Looks good in general, just fix some issues according to comments I've left

2020-05-08 09:52 UTC, marisita commented on HomeworkTen/CalculatorMethods.java
> +                throw new Exception("На ноль делить нельзя.");
There is no sense to throw an exception in try {}

2020-05-08 09:52 UTC, marisita commented on HomeworkTen/CalculatorMethods.java
> +        if (number2 != 0.0){
you don't have to compare number2 with 0.0, because number2 has int type (just compare with 0)

2020-05-08 09:52 UTC, marisita commented on HomeworkTen/CalculatorMethods.java
> +    public static int sub(int number1, int number2) {
not convenient name for the method, use verb without abbreviation

2020-05-08 09:52 UTC, marisita commented on HomeworkTen/CalculatorMethods.java
> +    public static int mul (int number1, int number2) {
not convenient name for the method, use verb without abbreviation

2020-05-08 09:52 UTC, marisita commented on HomeworkTen/CalculatorMethods.java
> +    public static double div (int number1, int number2) {
not convenient name for the method, use verb without abbreviation

2020-05-12 17:47 UTC, DariaChapek commented
@marisita The changes are committed, please check. Thanks.

2020-05-22 10:23 UTC, merged